---
title: "R Notebook"
output: html_notebook
---

Filtering of Brandenburg et. al dataset

## <https://www.biorxiv.org/content/10.1101/2025.08.12.669999v1.full>

here sp-Wnt5 is "LOC578814"\

```{r}

library(Seurat)
library(dplyr)
library(readr)
library(tidyr)

 #load your object from https://www-ncbi-nlm-nih-gov.uaccess.univie.ac.at/geo/query/acc.cgi

#choosing the stage. I chose 20 hpf
data_subset <- subset(GSE322501_merged_scRNA, subset = Stage == "Hpf20")

#sp-Wnt5 is "LOC578814"
genesofinterest <- c("LOC578814", "suPaxB", "Nk1", "IrxA")
gene.2 <- "FoxA"

#this part generates lists of factors coexpressed with the candidate, but not foxa

for (i in seq_along(genesofinterest)) {

  gene.1 <- genesofinterest[i]

  print(paste("Running", gene.1, "vs", gene.2))

  # cells expressing gene.1
  coi.gene.1 <- which(
    data_subset@assays$RNA@counts[gene.1, ] >= 1 #all cells with at least 1 read 
  )
  coi.gene.1 <- names(coi.gene.1)

  # cells expressing FoxA 
  coi.gene.2 <- which(
    data_subset@assays$RNA@counts[gene.2, ] >= 1 #(this treshold can be tweaked. I tried 1 and 3) 
  )
  coi.gene.2 <- names(coi.gene.2)

  # define expression groups
  coi.gene12 <- intersect(coi.gene.1, coi.gene.2)
  coi.gene1n2 <- setdiff(coi.gene.1, coi.gene.2)
  coi.gene2n1 <- setdiff(coi.gene.2, coi.gene.1)

  # assign cells to groups
  data_subset$groups <- "other"
  data_subset$groups[coi.gene1n2] <- "gene.1"
  data_subset$groups[coi.gene2n1] <- "gene.2"
  data_subset$groups[coi.gene12] <- "gene.1&2"

  #5 | set dataset clustering to these groups:
  data_subset1<-SetIdent(data_subset,value= 'groups')
  levels(data_subset1) #check that this worked; should list all of the    above groups

  #6 | run differential expression algorithm for each group:  
  all.markers <- FindAllMarkers(data_subset1,
                              logfc.threshold = 1, #minimum difference
                              return.thresh = 0.001,#maximum p-value
                              only.pos = T, #If you only want up-regulated
                              )

  # keep markers specific to gene.1-only cells
  all.markers_filtered <- all.markers %>%
  dplyr::filter(cluster == "gene.1")

  # saves as a table 
  readr::write_tsv(
  all.markers_filtered,
  paste0("Newest_FoxA_vs_", gene.1, ".tsv")
  )
}

```

generating annotation file (already created. see the file attached)

```{bash}
#  in shell: filtering ggf3 file to create annotations 
 grep "protein_id=" sp5_0_GCF.gff3 | cut -f 9 | perl -e 'use Data::Dumper; while(<STDIN>){chomp; my %h = (split(/[;=]/, $_)); printf("%s\t%s\t%s\n", $h{"gene"}, $h{"protein_id"}, $h{"Dbxref"})}'  > gene_prot_map_spup5_0.txt
```

```{r}

#adding annotations to the tf tables

library(tidyverse)

# annotation table: gene -> protein ID
mapTab <- read_tsv(
  "gene_prot_map_spur5_0.txt",
  col_names = FALSE,
  show_col_types = FALSE
)

# find all FoxA comparison files
files <- list.files(
  pattern = "^Newest_FoxA_vs_.*\\.tsv$",
  full.names = TRUE
)

for (file in files) {

  genes <- read_tsv(
    file,
    show_col_types = FALSE
  )

  intGenes <- genes %>%
    left_join(
      mapTab,
      by = c("gene" = "X1")
    ) %>%
    select(
      gene,
      X2,
      cluster,
      p_val_adj,
      avg_log2FC,
      pct.1,
      pct.2
    ) %>%
    distinct()

  # make output filename from input filename
  outfile <- sub(
    "\\.tsv$",
    "_protid.tsv",
    file
  )

  write_tsv(
    intGenes,
    outfile
  )

  print(paste("Saved:", outfile))
}

#you might need some deduplication after that step. I did it in excel...
```

\
Going for protein sequences to input into TF finder

```{bash}
# getting protein sequences in fasta 

for file in Newest_FoxA_vs_*_protid.tsv
do
    base="${file%_protid.tsv}"
    ids="${base}_ids.txt"
    out="${base}.fa"

    tail -n +2 "$file" |
        cut -f2 |
        grep -v "^NA$" |
        sort -u > "$ids"

    samtools faidx \
        -r "$ids" \
        sp5_0_GCF_proteins.fa > "$out"

    echo "Saved $out"
done

```

### **TF prediction using <https://guolab.wchscu.cn/AnimalTFDB4/#/TF_Predict>**

this piece creates a file with protein annotations (based on Spur5.0). It´s also attached as a file

```{bash}
grep '^>' sp5_0_GCF_proteins.fa |
sed 's/^>//' |
sed 's/ \[Strongylocentrotus purpuratus\]$//' |
awk '{
    id=$1;
    $1="";
    sub(/^ /,"");
    print id "\t" $0
}' > protein_descriptions.tsv
```

```{r}
# attaching annotations 
Foxa_vs_TF <- read_excel("Foxa_vs_TF.xlsx") #your table generated by TF finder

annotations <- read_tsv("protein_descriptions.tsv")

# Left join by Protein
Foxa_vs_TF_annotated <- Foxa_vs_TF %>%
  left_join(
    annotations %>% select(Protein, Description),
    by = "Protein"
  )

# Save result as TSV
write_tsv(
  Foxa_vsWnt5_TF_annotated,
  "Foxa_vs_TF_annotated.tsv"
)
```
